### ISSUE TITLE
Cannot find module '@angular/platform-browser/animations'.)

### ISSUE THREAD

**Issue by NikhilRadadiya** [devyumao/angular2-busy#59]
Hello @devyumao , I'm trying to use it with angular 2.4.0.
Updated animations to @angular/animations": "^4.1.3. but it still gives this error 

Cannot find module '@angular/platform-browser/animations'.)

can you please help? will it work with 2.4.0 version?

**Comment by tomerpeled** [comment]
Also encountered with this issue, any solution?

**Comment by NikhilRadadiya** [comment]
No

**Comment by tomerpeled** [comment]
Well, I succeed to solve it.

You should use angular2-busy "1.0.2" version and it's dependencies:

"angular2-busy": "1.0.2",
"ts-metadata-helper": "0.0.3",
"angular2-dynamic-component": "0.0.50"

**Comment by ghost** [comment]
It's because angular 4 doesn't ship with @angular/animations by default. Just run `npm install --save @angular/animations` and try again

**Comment by graham-sportsmgmt** [comment]
I just encountered this too - the docs should probably be updated to include the command mentioned by PatilSuraj..
