### ISSUE TITLE
AoT compilation issue

### ISSUE THREAD

**Issue by namlard** [devyumao/angular2-busy#81]
Hi !
I'm submitting you an issue i'm currently facing when i use your module. 
Here is the error log : 

> Error: ENOENT: no such file or directory, open '/home/nicolasa/project/dummy/dist/node_modules/angular2-busy/index.metadata.json'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at MetadataWriterHost.writeMetadata (/home/nicolasa/project/dummy/node_modules/@angular/tsc-wrapped/src/compiler_host.js:120:22)
    at MetadataWriterHost._this.writeFile (/home/nicolasa/project/dummy/node_modules/@angular/tsc-wrapped/src/compiler_host.js:97:23)
    at Object.writeFile (/home/nicolasa/project/dummy/node_modules/typescript/lib/typescript.js:67339:132)
    at Object.writeFile (/home/nicolasa/project/dummy/node_modules/typescript/lib/typescript.js:9117:14)
    at printSourceFileOrBundle (/home/nicolasa/project/dummy/node_modules/typescript/lib/typescript.js:64234:16)
    at emitSourceFileOrBundle (/home/nicolasa/project/dummy/node_modules/typescript/lib/typescript.js:64185:21)
    at Object.forEachEmittedFile (/home/nicolasa/project/dummy/node_modules/typescript/lib/typescript.js:9083:17)
    at Object.emitFiles (/home/nicolasa/project/dummy/node_modules/typescript/lib/typescript.js:64170:12)
Compilation failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-dummy@1.0.0 build: `ngc -p ./tsconfig-aot.json && npm run rollup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng-dummy@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nicolasa/.npm/_logs/2017-09-14T07_54_44_533Z-debug.log

You'll be able to find a small project that reproduce this issue at : https://embed.plnkr.co/IdODE3Wyz9oNuINfnYp7/

Can you give me a hand to know if it comes from your module or one of my config file ?

**Comment by Mattnmoore** [comment]
It seems like ng2-busy breaks AOT compilation. Is there a fix planned?

**Comment by mario-nguyen** [comment]
@Mattnmoore: This was fixed in this unmerged PR: https://github.com/devyumao/angular2-busy/pull/67.

**Comment by Mattnmoore** [comment]
Any plans to merge it in?

**Comment by yuechong** [comment]
ngx-busy

https://www.npmjs.com/package/ngx-busy

**Comment by gravypower** [comment]
moved to [ng-busy](https://github.com/victos/ng-busy) and it worked well with angular 5.2.0

**Comment by deyvidfk** [comment]
I do not understand why instead of trying to contribute to the current project by correcting the problems the developers create a project rewriting.

**Comment by gravypower** [comment]
@deyvidfk there is an open pull request to fix this (https://github.com/devyumao/angular2-busy/pull/67), this has been open since Jun 22, 2017. Maybe the author of ng-busy got sick of waiting for the pull request to be merged in.

**Comment by deyvidfk** [comment]
@gravypower There are several requests for correction, and due to abandonment, for each problem, new repositories are created from this.

Anyway, I also appreciate your contribution.

I definitely need something more stable. I'll look into if I can migrate to your repository and if I can help with something.
